# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3476a59ba13e02b3b115f5e781021b759cc09aea0d697eb032cf7b6227ee6913b5ce86b95880b8029e2b97d9f6e9814612faf46bfed4762be3a90acae008927

test:
  secret_key_base: ca71b39f071efe153e15e0745af373e5ee37a942697f437ae2edbdc7af27892ea0d70d4174dcedddf563b2d6ff65a7c8ff4dedaa9428fce6e1a0d6891cdd7ca5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
